name: Build Vue
on: [push]
jobs:
  build_vue:
    runs-on: ubuntu-latest
    name: Build Vue
    steps:
    - uses: actions/checkout@v2
    - id: Build-Vue
      uses: xRealNeon/VuePagesAction@1.0.1
    - name: Vue to Github Pages
      uses: xRealNeon/VuePagesAction@1.0.1
      with:
        username: nelson1995
        reponame: nelson-portfolio-site
        token: ${{ secrets.ACCESS_TOKEN }} # Generate PAT(personal Access token) and go to settings > secrets and variables > Actions and add it there. 
